---
resources:
  - name: my-timer
    type: time
    source:
      interval: 2m
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/petroill/concourse.git
      branch: master
      git_config:
      - name: safe.directory
        value: "*" # This allows all directories, use carefully

jobs:
  - name: job-hello-world
    public: true
    plan:
      - get: my-timer
        trigger: true
      - get: resource-tutorial
        trigger: true
      - task: hello-world
        file: resource-tutorial/tutorials/basic/task-hello-world/task_hello_world.yml